4-1
```{r}
customerExperience <- c('very happy','very happy','satisfied','satisfied','satisfied','very happy','bad','bad','satisfied','satisfied','bad','happy','happy','very happy','happy','happy','satisfied','very happy','very happy','satisfied','satisfied','very happy','satisfied','bad','very happy','very bad','very happy','bad','bad','very bad')
table(customerExperience)
levels(customerExperience)
```

```{r}
customerExperience_orderedsetup<-
  factor(customerExperience,
         levels=c('verybad','bad','satisfied','happy','very happy')
         ,ordered=T)
```

4-2

```{r}
datetime_boston<-
  lubridate::mdy_hm(
    c("10/13/2020 15:00", "4/10/2019 09:30"),
    tz="America/Bogota"
  )
datetime_mykonos<-
lubridate::mdy_hm(
  c("1/14/2021 03:27", "8/8/2020 11:20"),
  tz="Europe/Mariehamn")

dateTime_boston_atDeli <-
  lubridate::with_tz(
    datetime_boston,
    tz="Asia/Calcutta")
dateTime_mykonos_atDeli <-
  lubridate::with_tz(datetime_mykonos,tz="Asia/Calcutta")

```





4-3
```{r}
dfExercise <- list()

dataSet1 <- list(
  name=c("John", "Mary", "Ben"),
  age=c(33, 45, NA)
)
data.frame(dataSet1)
dataSet1<-dfExercise$data1.
```

```{r}
dataSet1$children[[1]][[1]] <-c(name="Jane",age=2)
dataSet1$children[[2]][[1]] <-c(name="Bill",age=3) 
dataSet1$children[[2]][[2]] <-c(name="Ken",age=0)
dataSet1$children[[3]][[1]] <-c(name="William",age=10)

```

4.5
```{r}
participations <- 
list('session 3',c("session 1", "session 2", "session 3"),'session 3',c("session 2", "session 1"),c("session 3", "session 1"),c("session 3", "session 2", "session 1"),'session 2','session 1',c("session 2", "session 1", "session 3"),c("session 3", "session 1", "session 2"))
```

```{r}
unlist(participations)->unlist_participations
class(unlist_participations)
table(unlist_participations)
```
4.6
```{r}
fct <- factor(
  c('參','貮','貮','貮','壹','貮','參','貮','參','參'),
  levels=c('壹','貮','參')
  )
as.numeric(fct)
sum(as.numeric(fct))
```
4.7
```{r}
Persian<-factor(
  c('۶','۹','۸','۹','۶','۸','۸','۵','۹','۹'),
  levels=c("۵", "۶", "۷", "۸", "۹")
)
as.numeric(Persian)
sum(as.numeric(Persian)+4)
```
4.8
```{r}
letter_grades <- c("C", "B-", "B", "B+", "A-", "A", "A+")
numeric_grades <- c(2, 2.5, 3, 3.5, 4, 4.5, 5)
studentGrades <- c('B','A','A+','B+','A-','B','B-','B','A+','B+','C','B-','B-','B','C','C','B+','B','B+','B')

factor(letter_grades,
       levels=letter_grades)
as.numeric(numeric_grades)
studentGrades <- c("C", "B-", "B", "B+", "A-", "A", "A+")
step1<-studentGrades[c(1,5)]
 step2<-c(2, 2.5, 3, 3.5, 4, 4.5, 5)[c(1,5)]
  
```
```{r}
studentLetterGrades <- {
  # Task map c("C", "B-", "B", "B+", "A-", "A", "A+") to c(2, 2.5, 3, 3.5, 4, 4.5, 5)
  
  # step1: for each grade in studentGrades find its position in c("C", "B-", "B", "B+", "A-", "A", "A+") so if studentGrades = c("C","A-"), step1 = c(1, 5) since c("C", "B-", "B", "B+", "A-", "A", "A+")[c(1, 5)] will give him "C", "A-"
  
  # step2: Use step1 result as position indices to retrieve from c(2, 2.5, 3, 3.5, 4, 4.5, 5). From previous example, step1=c(1, 5), then  c(2, 2.5, 3, 3.5, 4, 4.5, 5)[step1] will give him c(2, 4)
  
}
```

