```{r}
chr <- c('C','A','C','A','B','B','B','B','C')
table(chr) #table on character vector
table(as.factor(chr))
factor(
  chr,levels=c("C","B","A")
)
```

```{r}
newLevels <- 
{table(chr)->tb_chr # table check
  tb_chr
  #ask computer to figure out the level sequence
  sort(tb_chr,decreasing=T)->sorted_tb_chr
  # sort in decreasing order
  names(sorted_tb_chr)
  # take out table item names
  
}
```

```{r}
fct_chr <- factor(chr, levels=newLevels)
```

```{r}
f(x) # the same as
x |> f() # read as use x to do f

g(x, y) # the same as
x |> f(y)

g(f(x), y) # the same as
g(x |> f(x), y) # the same as
x |> f(x) |> g(y) # read as use x to do f, then (take the result) to do g
```
```{r}
newLevels <- 
{
  # table check
  tb_chr <- table(chr)
  # sort in decreasing order
  sorted_tb_chr <- sort(tb_chr, decreasing = T)
  # take out table item names
  names(sorted_tb_chr)
  
  # the same as ---
  
  chr |> 
    # table check
    ## read: take chr to do table
    table() |> 
    # sort in decreasing order
    ## read: then (with the result) 
    ##       to do sort
    sort(decreasing=T) |> 
    # take out table item names
    ## read: then (with the result)
    ##       to do names
    names()
}
fct_chr <- factor(chr, levels=newLevels)

```
```{r}
table(chr) -> tb_chr
sort(tb_chr, decreasing=T) -> sorted_tb_chr
names(sorted_tb_chr)
```
```{r}
chr |> 
  table() |> 
  sort(decreasing=T) |>
  names()
```

```{r}
library(magrittr) # import all the functions in this package
```
```{r}
df <-
data.frame(
  types = c('C','C','C','A','C','A','A','B','B','B','B','C'),
  response = c(83,59,54,68,64,88,72,73,66,94,53,55)
)
```
```{r}
df$types |> 
  factor() -> df$types

# the same as
df$types %<>% factor() # read: use df$types to do factor, then immediately save back
```
```{r}
df$type |> # read: use df$type, to do factor
  factor() %T>%  # then temporarily check print, then use the earlier result
    print() |> # to do table
  table()
```
```{r}
c(2, 3, -1) > c(3, 3, 5)
c(2, 3, -1) >= c(3, 3, 5)
```
```{r}
pick <- c(2, 3, -1) >= c(3, 3, 5)
c(2, 3, -1)[pick] 
sum(pick)
# pick element values that satisfy the criterion.
```
```{r}
income <- factor(
  c('20,001-30,000','20,001-30,000','less than 10,000','10,001-20,000','10,001-20,000','20,001-30,000','20,001-30,000','20,001-30,000'),
  levels=c("less than 10,000", "10,001-20,000", "20,001-30,000"),
  ordered = T)

income < "10,001-20,000"
income <= "10,001-20,000" 

pick <- income < "10,001-20,000"
income[pick]
which(pick)
```
```{r}
birthdays <- 
  lubridate::ymd(
    c('2017-11-29','2001-11-07','2011-03-30','2014-03-26','2011-04-20','2014-06-11')
  )

# born after 2002
pick <- birthdays > lubridate::ymd("2002-12-31")

birthdays[pick]
```
```{r}
pick <- c(5, NA, -1) > 0
pick
sum(pick)
sum(pick, na.rm = T)
```

```{r}
studentGradesInputFromTA <- 
  c(88, 52, 73)
studentGradesFromTeacherCalculation <-
  c(88, 51, 72)
pick<-studentGradesInputFromTA == 
  studentGradesFromTeacherCalculation
pick_wrong<-!pick



```
```{r}
whichIsTheSame <- 
  which(
    studentGradesInputFromTA == 
  studentGradesFromTeacherCalculation
  )
print(whichIsTheSame)
```
```{r}
# compare two character vectors
c("A", "B", "C") == c("B", "A", "C")
!(c("A", "B", "C") == c("B", "A", "C"))
c("A", "B", "C") != c("B", "A", "C")

# list is not atomic vector
list("John", 182, 35) == list("John", 182, 40)
```
```{r}
studentGradesInputFromTA2 <- c(
  82, NA, 73
)
studentGradesInputFromTA2 ==
  studentGradesFromTeacherCalculation

studentGradesFromTeacherCalculation2 <- c(
  82, NA, 73
)
studentGradesInputFromTA2 == 
  studentGradesFromTeacherCalculation2

identical(
  studentGradesInputFromTA2, 
  studentGradesFromTeacherCalculation2
)
```
```{r}
# long vector
long_vctr = c("A", "B", "C", "D")

# short vector
short_vctr = c(1, 2)
# recycle short_vctr
short_vctr_recycles = 
  c(c(1, 2), c(1, 2))[1:4]
short_vctr_recycles

# short vector
short_vctr2 = c(1, 2, 3)
# recycle short_vctr
short_vctr_recycles2 = 
  c(c(1, 2, 3), c(1, 2, 3))[1:4]
short_vctr_recycles2
```
```{r}
paste(c("Apr.", "May."), c("1", "1"))
# use recycling
paste(c("Apr.", "May."), "1")
```
```{r}
.years <- rep(1998:2021, each=2)
rep(1998,2021,2)
print(.years)
.monthdays <- c("01-01", "07-01")
.dates <- paste(.years, .monthdays, sep="-")
print(.dates)
```

```{r}
# 10 students' majors
majors <- c('economics','law','economics','sociology','sociology','sociology','sociology','economics','statistics','law')
# ? who are from the school of social science ?

# define a set of values that the school contain
set_schoolSocialScience = c("economics", "sociology", "social work")
pickSchoolSocialScience <-
  majors %in% set_schoolSocialScience
print(pickSchoolSocialScience)
which(pickSchoolSocialScience)
sum(pickSchoolSocialScience)
```

